<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;
class Category extends Controller
{
	protected $db;
	protected function _initialize ()
	{
		parent::_initialize (); // TODO: Change the autogenerated stub
		$this->db= new \app\common\model\Category();
	}

	//文章栏目的首页
	public function index(){
       //获取栏目的数据
         //$field=db('cate')->select ();
		$field=$this->db->getAll();
       //将获取到的数据分配到页面上
		 $this->assign ('field',$field);
		 //加载文章首页模板
		return $this->fetch ();
	}

	//文章栏目的添加

	public function store(){

		if (request ()->isPost ()){
			//halt (input ('post.'));
			$res=$this->db->store(input ('post.'));
			//判断
			if ($res['valid']){
				//操作成功
				$this->success ($res['msg'],'index');
			}else{
				$this->error ($res['msg']);
			}
		}
		return $this->fetch ();

	}

	//添加子级栏目
	public function addSon(){
       $cate_id=input ('param.cate_id');
       //halt ($cate_id);
		$data=$this->db->where('cate_id',$cate_id)->find();
		//halt ($data);
		$this->assign ('data',$data);
		if (request ()->isPost ()){
			$res=$this->db->store(input ('post.'));
			//判断
			if ($res['valid']){
				//操作成功
				$this->success ($res['msg'],'index');
			}else{
				$this->error ($res['msg']);
			}
		}

		return $this->fetch ();
	}


	public function edit(){
		if (request ()->isPost ()){
			//halt ($_POST);
			$res=$this->db->edit(input ('post.'));
			if ($res['valid']){
				//执行成功
				$this->success ($res['msg'],'index');
			}else{
                //执行失败
				$this->error ($res['msg']);
			}
		}
        //接收cate_id‘
		$cate_id=input ('param.cate_id');
		//halt ($cate_id);
		//获取旧数据
		$oldData=$this->db->find($cate_id);
		//分配到页面上
		$this->assign ('oldData',$oldData);
		//处理所属分类（不能包含自己	和自己的子集数据）
		$cateData=$this->db->getCateData($cate_id);
         //halt ($cateData);
		$this->assign ('cateData',$cateData);
		return $this->fetch ();
	}
	//删除栏目
	public function del(){

		$res=$this->db->del(input ('get.cate_id'));
		if ($res['valid']){
            $this->success ($res['msg'],'index');
		}else{
            $this->error ($res['msg']);
		}
	}
}
