<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;

class Link extends Controller
{
	protected $db;
	protected function _initialize ()
	{
		parent::_initialize (); // TODO: Change the autogenerated stub
		$this->db=new \app\common\model\Link();
	}

	/**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
		//获取首页所有数据
		$field=$this->db->getAll();
		//分配到页面
		$this->assign ('field',$field);
        return $this->fetch ();
    }

    //添加友链
	public function store()
	{
		$link_id=input ('param.link_id');
		if (\request ()->isPost ()){

			$res=$this->db->store(input('post.'));

			if ($res['valid']){
				//说明执行成功
				$this->success($res['msg'],'index');
			}else{
				//说明执行失败
				$this->error($res['msg']);
			}
		}
		if ($link_id){
               //说明是编辑
			$oldData=$this->db->find($link_id);
		}else{
             //说明是添加
			$oldData=['link_name'=>'','link_url'=>'','link_sort'=>100];
		}
		//分配到页面
		$this->assign ('oldData',$oldData);
		return $this->fetch ();
	}
	//删除友链
	public function del(){
		$link_id=input ('get.link_id');
		//执行删除
		if (\app\common\model\Link::destroy ($link_id)){
			//成功提示
			$this->success ('操作成功','index');
		}else{
			//失败提示
			$this->error ('操作失败');
		}


	}

}
