<?php

namespace app\admin\controller;

use think\Controller;

class Tag extends Controller
{
	protected $db;
	public function _initialize ()
	{
		parent::_initialize (); // TODO: Change the autogenerated stub
		$this->db = new \app\common\model\Tag();
	}

	//加载模板
	public function index(){
		// 查询标签所有数据 并且每页显示10条数据
		//$list = Db::name('user')->where('status',1)->paginate(10);
		$field = db ('tag')->paginate(5);
		//分配变量到页面上

		$this->assign('field',$field);
		return $this->fetch ();
   }

   //添加标签
	public function store(){
		//通过有没有$tag_id来判断是编辑标签还是添加标签
		$tag_id=input ('param.tag_id');
		if (request ()->isPost ()){
			//halt ($_POST);
			$res=$this->db->store(input ('post.'));
			if ($res){
				//说明执行成功
				$this->success ($res['msg'],'index');
			}else{
                //执行失败
				$this->error ($res['msg']);
			}
		}

		if ($tag_id){
            //说明是在编辑请求
			$oldData=$this->db->find($tag_id);
		}else{
           //说明是在添加请求
			$oldData=['tag_name'=>''];
		}
		$this->assign ('oldData',$oldData);
		return $this->fetch ();
	}

	//标签删除
	public function del(){
         $tag_id=input ('get.tag_id');
         //执行删除
       if (\app\common\model\Tag::destroy ($tag_id)){
       	    //成功提示
		   $this->success ('操作成功','index');
	   }else{
       	//失败提示
		   $this->error ('操作失败');
	   }
	}
}

