<?php
namespace app\index\controller;

use think\Controller;

class Article extends Controller
{
    protected $db;
    public function _initialize ()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->db = new \app\common\model\Article();
    }
	public function index()
	{
        //获取首页所有数据
        $field=$this->db->getAll();
        //分配到页面
        $this->assign ('field',$field);
        return $this->fetch ();
	}
	//文章列表
	public function list(){

		return $this->fetch ();
	}
}