<?php
namespace app\index\controller;

class Index extends Common
{
    protected $db;
    public function _initialize ()
    {
        parent::_initialize (); // TODO: Change the autogenerated stub

        $this->db= new \app\common\model\Article();
    }

    public function index()
    {
		$headConf=['title'=>'陶太富博客--首页'];
		$this->assign ('headConf',$headConf);
        $srchtxt=input('srchtxt');
        $tag_id=input ('param.tag_id');
        $limit=input('limit');
        $limit=4;
        if($srchtxt){
            //模糊查询
            $where['title'] = ['like', "%".$srchtxt."%"];
        }
        //获取文章数据
		$articleData=db ('article')
            ->alias ('a')
			->join ('__CATE__ c','a.cate_id=c.cate_id')
            ->where ('a.is_recycle',2)
            ->order('sendtime desc')
            ->paginate(8)
            ->each(function($item, $key){
                $item['tags'] = db ('arc_tag')->alias ('at')
                    ->join ('__TAG__ t','at.tag_id=t.tag_id')
                    ->where ('at.arc_id',$item['arc_id'])->column ('t.tag_id,t.tag_name');
                foreach ($item as $k=>$v) $item[]=isset($v['tag_name']) ?$v['tag_name'] : '';
                return $item;
            });
        $page = $articleData->render();
        //赋值到模板
        $this->assign([
            'srchtxt' =>$srchtxt,
            'limit' =>$limit,
            'page' =>$page,
            'articleData' =>$articleData,
        ]);
        $this->assign ('articleData',$articleData);
    	return $this->fetch ();
    }

    public function hello(){
        return $this->fetch ();
    }
}
